### ISSUE TITLE
Using Jackson modules

### ISSUE THREAD

**Issue by filiphr** [vojtechhabarta/typescript-generator#110]
I just started using this typescript-generator, and I must say it is a really good tool for full stack development.

I couldn't find anything regarding usage of different Jackson modules. For example, we use the Jackson [hibernate5](https://github.com/FasterXML/jackson-datatype-hibernate) module that ignores `javax.persistence.Transient` for example. 

How complex, would it be to add support something like this?

**Comment by vojtechhabarta** [comment]
@filiphr finally it was straightforward. Since typescript-generator uses JSON library (in this case Jackson2) to obtain list of bean properties it was only needed to register modules in `ObjectMapper`.

I used `ObjectMapper.findModules()` with appropriate classloader to **discover all modules** on classpath.

Could you please try it if it meets your needs?
Thanks

**Comment by filiphr** [comment]
@vojtechhabarta awesome thanks for the quick feedback and support. I will be able to try it out on Monday (it is work code 😄). Will let you know if it works as we need it then.

What you could do to make it more flexible is to have the possibility to pass the modules you want to be registered (not a deal breaker for us 😄). I am not sure if this is something interesting for someone, or just complicates the configuration...

**Comment by vojtechhabarta** [comment]
Yes, list of Jackson modules in configuration would be more flexible but I would wait until somebody asks for it.

**Comment by filiphr** [comment]
@vojtechhabarta it works great, exactly as expected. 

When are you planning to make a release with this new feature included?

**Comment by vojtechhabarta** [comment]
I tried it on some project with Jackson module and it failed with an exception:
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.15-SNAPSHOT:generate (rest) on project <xxx>: Execution rest of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.15-SNAPSHOT:generate failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution rest of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.15-SNAPSHOT:generate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.datatype.jdk8.Jdk8TypeModifier.modifyType(Jdk8TypeModifier.java:30)
	at com.fasterxml.jackson.databind.type.TypeFactory._constructType(TypeFactory.java:525)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:470)
	at com.fasterxml.jackson.databind.cfg.MapperConfig.constructType(MapperConfig.java:280)
	at com.fasterxml.jackson.databind.cfg.MapperConfig.introspectClassAnnotations(MapperConfig.java:310)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:674)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:545)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:361)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:272)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:225)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:153)
	at cz.habarta.typescript.generator.parser.Jackson2Parser.getBeanHelper(Jackson2Parser.java:202)
	at cz.habarta.typescript.generator.parser.Jackson2Parser.parseBean(Jackson2Parser.java:52)
	at cz.habarta.typescript.generator.parser.ModelParser.parseQueue(ModelParser.java:57)
	at cz.habarta.typescript.generator.parser.ModelParser.parseModel(ModelParser.java:32)
	at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:49)
	at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:41)
	at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:366)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

Fortunately upgrading Jackson2 to latest version (2.8.6) solved the problem.

Although my confidence with Jackson module discovery and registration is now lower I decided to leave it as default typescript-generator behavior.

Could you please try it again with latest changes?
Thanks

**Comment by filiphr** [comment]
@vojtechhabarta It still works. The thing is that I was using Jackson 2.8.6 from start. I also have the `Hibernate5Module`, `Jdk8Module` and the `JavaTimeModule` on my classpath. I think that it was some bug in the module `Jdk8Module` and not in the module discovery and registration.

**Comment by vojtechhabarta** [comment]
@filiphr thanks.

What I meant was that upgrading Jackson dependency **in typescript-generator** helped. Tested project still uses older Jackson version. So I am not sure where the problem exactly was.

Released [v1.16.274](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.16.274).

**Comment by vojtechhabarta** [comment]
@filiphr there is some problem with automatic module registration - `JaxbAnnotationIntrospector` interferes with `JacksonAnnotationIntrospector`. To prevent this problem I changed the behavior and now modules are **not** loaded automatically. This is incompatible change, sorry for that.

Release [v1.29.355](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.29.355) adds these parameters:
- `jackson2ModuleDiscovery` - turns on previous behavior
- `jackson2Modules` - specifies list of modules as you suggested

I think Maven configuration example could be:
``` xml
<configuration>
    <jsonLibrary>jackson2</jsonLibrary>
    <jackson2Modules>
        <module>com.fasterxml.jackson.datatype.hibernate5.Hibernate5Module</module>
    </jackson2Modules>
</configuration>
```

This change was part of #183.

**Comment by filiphr** [comment]
Thanks for the heads up and the detailed write up @vojtechhabarta.
