### ISSUE TITLE
Error on running plugin with maven

### ISSUE THREAD

**Issue by fplini** [vojtechhabarta/typescript-generator#133]
Hi! We're running this plugin to generate some typescript classes from java classes.
I use a function for customTypeNamingFunction and all works fine on 2 machines.
On a third machine the plugin fails, seems to have some problems on running any type o js function in customTypeNamingFunction.
This is the stacktrace:
`[ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.23.311:generate (generate) on project easy-frontend: Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.23.311:generate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.23.311:generate (generate) on project easy-frontend: Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.23.311:generate failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:1.23.311:generate failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at cz.habarta.typescript.generator.compiler.SymbolTable.getCustomTypeNamingFunction(SymbolTable.java:156)
        at cz.habarta.typescript.generator.compiler.SymbolTable.getMappedName(SymbolTable.java:117)
        at cz.habarta.typescript.generator.compiler.SymbolTable.resolveSymbolNames(SymbolTable.java:82)
        at cz.habarta.typescript.generator.compiler.ModelCompiler.javaToTypeScript(ModelCompiler.java:84)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:52)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:43)
        at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:470)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
`

Anyone know what's the problem? I supposed that could be a jdk's problem but tried other jdks and the problem persists

**Comment by vojtechhabarta** [comment]
Could you please try version [1.24.315](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v1.24.315) (it improves ScriptEngine handling) and if it still doesn't work in your case copy&paste relevant part of output here? Can you please also include `mvn --version` output?

**Comment by fplini** [comment]
Hi! Yesterday we tried to uninstall idea and delete local repo. Re-initialize all and seems to work now.. But it was strange. I'm going to try this new version!

**Comment by vojtechhabarta** [comment]
Closing old issues after release. Feel free to reopen if needed.
