### ISSUE TITLE
Wrong jar packaging in 2.1.410: Class AnnotationIntrospector class not found

### ISSUE THREAD

**Issue by harry-kalligeros** [vojtechhabarta/typescript-generator#225]
The latest version 2.1.410 of the plugin does not work, the command fails with the message
ClassDefNotFoundException: Class AnnotationIntrospector class not found

It worked with the previous version.

Please provide a fix.

**Comment by harry-kalligeros** [comment]
Exactly. It worked with 2.1.406

Here is the stack trace:

```
Running TypeScriptGenerator version 2.1.410
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.807 s
[INFO] Finished at: 2018-04-13T16:29:56+03:00
[INFO] Final Memory: 19M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410:generate (default-cli) on project r4bp-api: Execution default-cli of goal cz.habarta.typescript-g
enerator:typescript-generator-maven-plugin:2.1.410:generate failed: A required class was missing while executing cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410:generate: com/f
asterxml/jackson/databind/AnnotationIntrospector
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-maven-plugin/2.1.410/typescript-generator-maven-plugin-2.1.410.jar
[ERROR] urls[1] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[2] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[3] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[4] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[5] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
[ERROR] urls[6] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[8] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[9] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-core/2.1.410/typescript-generator-core-2.1.410.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: com.fasterxml.jackson.databind.AnnotationIntrospector
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410:generate (default-cli) on project r4bp-api: Execu
tion default-cli of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410:generate failed: A required class was missing while executing cz.habarta.typescript-generator:typescrip
t-generator-maven-plugin:2.1.410:generate: com/fasterxml/jackson/databind/AnnotationIntrospector
-----------------------------------------------------
realm =    plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-maven-plugin/2.1.410/typescript-generator-maven-plugin-2.1.410.jar
urls[1] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[2] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[3] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[4] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[5] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
urls[6] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-core/2.1.410/typescript-generator-core-2.1.410.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410:generate failed: A required class was
 missing while executing cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410:generate: com/fasterxml/jackson/databind/AnnotationIntrospector
-----------------------------------------------------
realm =    plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-maven-plugin/2.1.410/typescript-generator-maven-plugin-2.1.410.jar
urls[1] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[2] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[3] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[4] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[5] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
urls[6] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-core/2.1.410/typescript-generator-core-2.1.410.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:168)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410:generate: com/fasterxm
l/jackson/databind/AnnotationIntrospector
-----------------------------------------------------
realm =    plugin>cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.1.410
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-maven-plugin/2.1.410/typescript-generator-maven-plugin-2.1.410.jar
urls[1] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[2] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[3] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[4] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[5] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
urls[6] = file:/C:/Users/xxxxx/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/C:/Users/xxxxx/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/C:/Users/xxxxx/.m2/repository/cz/habarta/typescript-generator/typescript-generator-core/2.1.410/typescript-generator-core-2.1.410.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:166)
        ... 21 more
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/AnnotationIntrospector
        at cz.habarta.typescript.generator.TypeScriptGenerator.createModelParser(TypeScriptGenerator.java:104)
        at cz.habarta.typescript.generator.TypeScriptGenerator.getModelParser(TypeScriptGenerator.java:94)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:51)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:43)
        at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:593)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.AnnotationIntrospector
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 27 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by vojtechhabarta** [comment]
That's strange, I don't see any suspicious change since 2.1.406 [https://github.com/vojtechhabarta/typescript-generator/compare/v2.1.406...master](https://github.com/vojtechhabarta/typescript-generator/compare/v2.1.406...master).

Is it possible that Maven didn't download new version correctly?
Could you please try to delete typescript-generator in you local Maven repository at `HOME/.m2/repository/cz/habarta/typescript-generator` and retry?

**Comment by harry-kalligeros** [comment]
You're right. It seems that something has not been downloaded completely. I close the issue.

**Comment by vojtechhabarta** [comment]
Great to know you solved it, thanks for the response.
