### ISSUE TITLE
Can't generate typescript based on dependent jar

### ISSUE THREAD

**Issue by cjnygard** [vojtechhabarta/typescript-generator#264]
For some reason, I cannot get typescript-generator to create client proxies for code which is referenced in a dependency package.  The same configuration running within the package where the code is built works fine.  Creating a separate sub-module which pulls in the required package via dependency eventually throws an exception in the jackson annotation processing:

```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:77)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getDeclaredAnnotations(Class.java:3477)
	at com.fasterxml.jackson.databind.util.ClassUtil.findClassAnnotations(ClassUtil.java:1072)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolveClassAnnotations(AnnotatedClassResolver.java:153)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolveFully(AnnotatedClassResolver.java:117)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClassResolver.resolve(AnnotatedClassResolver.java:69)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector._resolveAnnotatedClass(BasicClassIntrospector.java:282)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:191)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:92)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:16)
	at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:778)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:135)
	at cz.habarta.typescript.generator.parser.Jackson2Parser.getBeanHelper(Jackson2Parser.java:262)
	at cz.habarta.typescript.generator.parser.Jackson2Parser.parseBean(Jackson2Parser.java:84)
	at cz.habarta.typescript.generator.parser.Jackson2Parser.parseClass(Jackson2Parser.java:77)
	at cz.habarta.typescript.generator.parser.ModelParser.parseQueue(ModelParser.java:66)
	at cz.habarta.typescript.generator.parser.ModelParser.parseModel(ModelParser.java:35)
	at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:61)
	at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:53)
	at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:644)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo
```

**Comment by vojtechhabarta** [comment]
Is this still a problem?
Could you please try [v2.7.447](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.7.447)?

**Comment by vojtechhabarta** [comment]
Hopefully this was just a problem with some Java versions mismatch.
