### ISSUE TITLE
NullPointerException when superclass is mapped to a primitive

### ISSUE THREAD

**Issue by Yona-Appletree** [vojtechhabarta/typescript-generator#348]
Given a custom type mapping of a superclass to a primitive:

    // In build.gradle.kts, for example
    customTypeMappings = listOf(
        "org.test.SuperType:string"
    )

Or when using a `customTypeProcessor` that does the same.

typescript-generator will crash with a `NullPointerException` when it attempts to map a subclass (Use Kotlin to avoid these types of issues! ;):

    Caused by: java.lang.NullPointerException
        at cz.habarta.typescript.generator.compiler.ModelCompiler.mappedToClass(ModelCompiler.java:248)
        at cz.habarta.typescript.generator.compiler.ModelCompiler.processBean(ModelCompiler.java:193)
        at cz.habarta.typescript.generator.compiler.ModelCompiler.processModel(ModelCompiler.java:157)
        at cz.habarta.typescript.generator.compiler.ModelCompiler.javaToTypeScript(ModelCompiler.java:58)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:67)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:57)
        at cz.habarta.typescript.generator.gradle.GenerateTask.generate(GenerateTask.java:196)

This occurs because `getOriginClass(symbolTable, parentType)` can return `null` and `mappedToClass()` does not handle nulls. 

I'll submit a PR to fix this basic case, but some further thought might be given into handling of polymorphic custom type mappings.

**Comment by vojtechhabarta** [comment]
@Yona-Appletree your fix for this problem is released in [2.15](https://github.com/vojtechhabarta/typescript-generator/releases).
Thanks again.
