### ISSUE TITLE
JetBrains @Nullable annotation support

### ISSUE THREAD

**Issue by RobbinBaauw** [vojtechhabarta/typescript-generator#419]
Hi,

This is the same request as #173.

Being: would it be possible to flag `@org.jetbrains.annotations.Nullable` as an optional JSON annotation? When putting it in the `optionalAnnotations` it doesn't work (probably because of the `RetentionPolicy.CLASS`).

Thanks!

**Comment by RobbinBaauw** [comment]
I've looked at this and it seems impossible to support `RetentionPolicy.CLASS` for this library.

There are a few other options though:
- Writing parts of the library in Kotlin, thus allowing us to use their reflection "natively"
- Calling Kotlin reflection from Java, using a [util class something like this](https://github.com/spring-projects/spring-framework/pull/1242/files#diff-244315b45582a5b7573a15644b16c373)

Either way I would be willing to make a PR. In both cases new dependencies will have to be added, either the Kotlin plugin or the kotlin-reflect dependency.

I'd like to hear your thoughts about this

**Comment by vojtechhabarta** [comment]
I was thinking about second option (using Kotlin reflection from Java). But first I wanted to investigate it myself. I think minimally we would need to add `org.jetbrains.kotlin:kotlin-reflect` dependency plus 3 transitive dependencies, right? Is there a reason why to add also Kotlin plugin?

**Comment by RobbinBaauw** [comment]
I think `org.jetbrains.kotlin:kotlin-reflect` should be enough yes, we would need the Kotlin plugin if we wanted to write Kotlin.

**Comment by RobbinBaauw** [comment]
Hi, I'm running this on a real project now where my version used to work, and I get a `StackOverflowError`.

```
Cause: java.lang.StackOverflowError
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
	at kotlin.reflect.jvm.internal.KTypeImpl.getClassifier(KTypeImpl.kt)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:207)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getTypes$5(TypeParser.java:244)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getTypes(TypeParser.java:245)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:229)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getBareType$4(TypeParser.java:221)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:222)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getTypes$5(TypeParser.java:244)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getTypes(TypeParser.java:245)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:229)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getBareType$4(TypeParser.java:221)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:222)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getTypes$5(TypeParser.java:244)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getTypes(TypeParser.java:245)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:229)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getBareType$4(TypeParser.java:221)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:222)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getTypes$5(TypeParser.java:244)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getTypes(TypeParser.java:245)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:229)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getType(TypeParser.java:202)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.lambda$getBareType$4(TypeParser.java:221)
	at cz.habarta.typescript.generator.parser.TypeParser$KotlinTypeParser.getBareType(TypeParser.java:222)
```

I'll try to figure out what is going on and come back with more information

**Comment by vojtechhabarta** [comment]
Thanks for the example. I didn't know that you added it because GitHub only sends notification when comment is added and not edited.
I will try to fix it.

**Comment by RobbinBaauw** [comment]
Thanks! Could you maybe release this to maven central?

**Comment by vojtechhabarta** [comment]
Sure, released [2.19.577](https://github.com/vojtechhabarta/typescript-generator/releases/tag/v2.19.577).

**Comment by RobbinBaauw** [comment]
Thanks! It works perfectly now

**Comment by RobbinBaauw** [comment]
Closing because it works.
