### ISSUE TITLE
No input classes found.

### ISSUE THREAD

**Issue by mirceaagr** [vojtechhabarta/typescript-generator#494]
Hello, when running the goal I get an error `No input classes found`
`[INFO] --- typescript-generator-maven-plugin:2.24.612:generate (default-cli) @ av-mrh-abs-bff ---
Running TypeScriptGenerator version 2.24.612
Error: Cannot load class 'cz.habarta.typescript.generator.Person'
java.lang.ClassNotFoundException: cz.habarta.typescript.generator.Person
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cz.habarta.typescript.generator.Input.loadClasses(Input.java:212)
	at cz.habarta.typescript.generator.Input.fromClassNames(Input.java:198)
	at cz.habarta.typescript.generator.Input.from(Input.java:93)
	at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:897)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Error: No input classes found.
`

**Comment by mirceaagr** [comment]
NVM.. after reading the docs figure it out..

**Comment by zx-spectrum-48k** [comment]
Could you elaborate more what was the problem? I'm trying to run typescript-generator via maven using configuration examples from the docs but to no avail. I modified example to describe my java class which I want to be converted. I used also classPattern approach but generator still throws java.lang.ClassNotFoundException
