### ISSUE TITLE
Error: No input classes found. in CI/CD for typescript-generator v2.24.612

### ISSUE THREAD

**Issue by Stetchy** [vojtechhabarta/typescript-generator#504]
Hi

While running the following maven goal in Jenkins, I receive the below stacktrace. This Maven goal works fine on my local machine.

`mvn typescript-generator:generate`

<details> <summary>Stack trace</summary> 

```
Running TypeScriptGenerator version 2.24.612
Error: Cannot load class 'com.package.QuoteResponse'
java.lang.ClassNotFoundException: com.package.QuoteResponse
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at cz.habarta.typescript.generator.Input.loadClasses(Input.java:212)
	at cz.habarta.typescript.generator.Input.fromClassNames(Input.java:198)
	at cz.habarta.typescript.generator.Input.from(Input.java:93)
	at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:897)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Error: Cannot load class 'com.package.RetrieveQuoteResponse'
java.lang.ClassNotFoundException: com.package.RetrieveQuoteResponse
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at cz.habarta.typescript.generator.Input.loadClasses(Input.java:212)
	at cz.habarta.typescript.generator.Input.fromClassNames(Input.java:198)
	at cz.habarta.typescript.generator.Input.from(Input.java:93)
	at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:897)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Error: No input classes found.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49:01 min
[INFO] Finished at: 2020-07-27T16:32:42+01:00
[INFO] Final Memory: 58M/210M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.24.612:generate (default-cli) on project motorquoteorchestrator: Execution default-cli of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.24.612:generate failed: No input classes found. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

</details>

<details> <summary>pom.xml</summary>

```xml
        <plugin>
          <groupId>cz.habarta.typescript-generator</groupId>
          <artifactId>typescript-generator-maven-plugin</artifactId>
          <executions>
            <execution>
              <id>generate</id>
              <goals>
                <goal>generate</goal>
              </goals>
              <phase>process-classes</phase>
            </execution>
          </executions>
          <configuration>
            <noEslintDisable>true</noEslintDisable>
            <noTslintDisable>true</noTslintDisable>
            <noFileComment>true</noFileComment>
            <jsonLibrary>jackson2</jsonLibrary>
            <classes>
              <class>com.package.QuoteResponse</class>
              <class>com.package.RetrieveQuoteResponse</class>
            </classes>
            <outputKind>global</outputKind>
            <outputFile>index.d.ts</outputFile>
          </configuration>
        </plugin>
```

</details>

Any ideas why this may be happening? I'm using Java 11 and Maven 3 both locally and in Jenkins.

**Comment by vojtechhabarta** [comment]
Hi,

I think you can reproduce the situation locally with `mvn clean`. Build should then behave the same as on Jenkins.

1. You can run typescript-generator as part of `process-classes` lifecycle phase (because you already have it defined in pom.xml `<execution>` element): `mvn process-classes` or `mvn install`.

2. Or you can run just `mvn typescript-generator:generate` but you need to first compile your classes for example like this: `mvn compile typescript-generator:generate`. In this case you don't need the `<execution>` element in pom.xml.

I would prefer first way if you want it to be part of normal build (`mvn install`). If you want it only run "on demand" I would use second way.
