### ISSUE TITLE
Getting stackover flow error with version 2.32.889

### ISSUE THREAD

**Issue by nithinprasad** [vojtechhabarta/typescript-generator#695]
When i tried generating i am getting 
`Exception in thread "main" java.lang.StackOverflowError
        at cz.habarta.typescript.generator.util.GenericsResolver$ResolvedClass.resolveType(GenericsResolver.java:141)
        at cz.habarta.typescript.generator.util.GenericsResolver$ResolvedClass.resolveAncestor(GenericsResolver.java:131)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at cz.habarta.typescript.generator.util.GenericsResolver$ResolvedClass.getDirectAncestors(GenericsResolver.java:117)
        at cz.habarta.typescript.generator.util.GenericsResolver.traverseSomeInheritancePath(GenericsResolver.java:86)
        at cz.habarta.typescript.generator.util.GenericsResolver.resolveBaseGenericVariables(GenericsResolver.java:55)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:186)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:187)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processType(DefaultTypeProcessor.java:96)
        at cz.habarta.typescript.generator.TypeProcessor$Chain.processType(TypeProcessor.java:126)
        at cz.habarta.typescript.generator.TypeProcessor$Context.processTypeInsideCollection(TypeProcessor.java:65)
        at cz.habarta.typescript.generator.DefaultTypeProcessor.processKnownGenericType(DefaultTypeProcessor.java:1`

Goals are 
` <build>
	<plugins>
		<plugin>
    <groupId>cz.habarta.typescript-generator</groupId>
    <artifactId>typescript-generator-maven-plugin</artifactId>
     <version>2.32.889</version>
    <configuration>
        
    </configuration>
    <executions>
        <execution>
            <id>generate</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <jsonLibrary>jackson2</jsonLibrary>
                  <classPatterns>
                    <pattern>tcsbancs.digital.*</pattern>
                    <pattern>tcsbancs.digital.**</pattern>
                    <pattern>cz.habarta.example.rest.*</pattern>
                </classPatterns>
                <outputFile>target/sample.d.ts</outputFile>
                <outputKind>module</outputKind>
            </configuration>
        </execution>
    </executions>
</plugin>

	</plugins>
  </build>`

When i tried the same using 2.0.400

Getting

`[ERROR] Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.0.400:generate (generate) on project kernel-impl.customer: Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.0.400:generate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.0.400:generate (generate) on project kernel-impl.customer: Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.0.400:generate failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:318)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate of goal cz.habarta.typescript-generator:typescript-generator-maven-plugin:2.0.400:generate failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at cz.habarta.typescript.generator.compiler.ModelCompiler.mappedToClass(ModelCompiler.java:224)
        at cz.habarta.typescript.generator.compiler.ModelCompiler.processBean(ModelCompiler.java:169)
        at cz.habarta.typescript.generator.compiler.ModelCompiler.processModel(ModelCompiler.java:133)
        at cz.habarta.typescript.generator.compiler.ModelCompiler.javaToTypeScript(ModelCompiler.java:52)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:52)
        at cz.habarta.typescript.generator.TypeScriptGenerator.generateTypeScript(TypeScriptGenerator.java:43)
        at cz.habarta.typescript.generator.maven.GenerateMojo.execute(GenerateMojo.java:593)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
`

**Comment by vojtechhabarta** [comment]
Thanks for the bug report. Could you please try to isolate the class (or classes) which causes the problem? (I am not able to reproduce it.)
