### ISSUE TITLE
Gradle Integration not working?

### ISSUE THREAD

**Issue by georgeedwards** [vojtechhabarta/typescript-generator#79]
I am trying to use this project to generate a `.d.ts` file to describe this [Azure](https://github.com/Azure/azure-mobile-apps-android-client) `.jar` SDK.  So following your notes, 
1. I changed the global sdk's **build.gradle** from [this](https://github.com/Azure/azure-mobile-apps-android-client/blob/master/sdk/build.gradle) to [this](https://gist.github.com/georgeedwards/fb5249644fa66a1ecfab10859148de02). 
2. However, on build no sample.d.ts file is created. Given the notes about not including project specific dependencies in there, I tried to change [this](https://github.com/Azure/azure-mobile-apps-android-client/blob/master/sdk/src/sdk/build.gradle) file to [this](https://gist.github.com/georgeedwards/dd278adf865c593728cd573fd0281156) however, again no definition file was produced. 

Am I doing something wrong, or is this a bug?

**Comment by vojtechhabarta** [comment]
When you run for example `gradle build` you should see
```
:generateTypeScript
Running TypeScriptGenerator version ...
```
in build output. Is this the case? Do you see any errors in build output?

You can also try to clone typescript-generator from github and build `sample-gradle` module and compare the output.

**Comment by georgeedwards** [comment]
Well if I run it from the root of the project, then there are no errors - but to reference to `generateTypeScript ` However, if I run in any of the subdirectories, I get errors relating to the ZumoE2E tests, but I assume that to do with the azure SDK not this tool. From the project root (where the sdk docs say to build from), build.gradle if I add the `generateTypeScript {...` funtion to the `buildscript {` section, I get the error:

> Error:(26, 0) Could not find method generateTypeScript() for arguments [build_57fnw3ae6cntdti0aty98b09g$_run_closure1$_closure4@b01384b] on object of type org.gradle.api.internal.initialization.DefaultScriptHandler.
<a href="openFile:/Users/georgeedwards/source/repos/azure-mobile-apps-android-client/sdk/build.gradle">Open File</a>

**Comment by vojtechhabarta** [comment]
It seems that Gradle cannot find 'typescript-generator-gradle-plugin'.
Maybe you can try to add `mavenCentral()` to `buildscript` / `repositories`.

**Comment by georgeedwards** [comment]
Same result with mavenCentral added...

**Comment by georgeedwards** [comment]
If I change the DSK subproject's build.gradle to:

```
apply plugin: 'com.android.library'
apply plugin: 'java'
apply plugin: 'cz.habarta.typescript-generator'

version = '1.0'
sourceCompatibility = 1.7
targetCompatibility = 1.7

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: 'cz.habarta.typescript-generator', name: 'typescript-generator-gradle-plugin', version: '1.10.220'
    }
}

generateTypeScript {
    outputFile = 'build/sample.d.ts'
    classes = [
            'com.microsoft.windowsazure'
    ]
    jsonLibrary = 'jackson2'
    outputKind = 'global'
    namespace = 'GradleSample';
//    declarePropertiesAsOptional = false
//    removeTypeNameSuffix = 'Json'
//    mapDate = 'asNumber'
}

ext {
    PUBLISH_ARTIFACT_ID = 'azure-mobile-android'
}

group = 'com.microsoft.azure'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.1'

    defaultConfig {
        minSdkVersion 9
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.guava:guava:18.0'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    classpath group: 'cz.habarta.typescript-generator', name: 'typescript-generator-gradle-plugin', version: '1.10.220'
}

apply from : '../../android-libraries.gradle'

```

then I get the error:

>Error:(69, 0) Could not find method classpath() for arguments [{group=cz.habarta.typescript-generator, name=typescript-generator-gradle-plugin, version=1.10.220}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
<a href="openFile:/Users/georgeedwards/source/repos/azure-mobile-apps-android-client/sdk/src/sdk/build.gradle">Open File</a>

**Comment by georgeedwards** [comment]
@vojtechhabarta Any ideas? I would really love to get this working...

**Comment by vojtechhabarta** [comment]
@georgeedwards I am not Gradle expert, I don't use Gradle.

Can anybody help?

**Comment by georgeedwards** [comment]
@vojtechhabarta Maybe you could have a go with that repo just to make sure I'm not doing anything stupid?

**Comment by vojtechhabarta** [comment]
@georgeedwards which repo do you mean? Links provided in the first comment doesn't work (404). Can you provide new link? I will check it.

**Comment by georgeedwards** [comment]
@vojtechhabarta awesome, thanks! [Here](https://github.com/Azure/azure-mobile-apps-android-client) is the Github Repo

**Comment by vojtechhabarta** [comment]
@georgeedwards Unfortunately I wasn't successful either, SDK build is failing even without typescript-generator :(

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type org.gradle.invocation.DefaultGradle_Decorated.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.internal.reflect.ObjectInstantiationException: Could not create an instance of type org.gradle.invocation.DefaultGradle_Decorated.
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.initialization.DefaultGradleLauncherFactory.doNewInstance(DefaultGradleLauncherFactory.java:136)
        at org.gradle.initialization.DefaultGradleLauncherFactory.newInstance(DefaultGradleLauncherFactory.java:102)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:38)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.lang.ClassFormatError: Invalid pc in LineNumberTable in class file groovy/lang/MetaClassImpl
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:120)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:73)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:65)
        at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:34)
        at org.gradle.api.internal.plugins.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:28)
        at org.gradle.api.internal.plugins.DefaultConvention.<init>(DefaultConvention.java:36)
        at org.gradle.api.internal.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:66)
        at org.gradle.api.internal.AsmBackedClassGenerator$MixInExtensibleDynamicObject.<init>(AsmBackedClassGenerator.java:905)
        at org.gradle.invocation.DefaultGradle_Decorated.getAsDynamicObject(Unknown Source)
        at org.gradle.invocation.DefaultGradle_Decorated.getConvention(Unknown Source)
        at org.gradle.invocation.DefaultGradle_Decorated.getConventionMapping(Unknown Source)
        at org.gradle.invocation.DefaultGradle_Decorated.getServices(Unknown Source)
        at org.gradle.invocation.DefaultGradle_Decorated.getListenerManager(Unknown Source)
        at org.gradle.invocation.DefaultGradle.<init>(DefaultGradle.java:67)
        at org.gradle.invocation.DefaultGradle_Decorated.<init>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:49)
        ... 28 more

```

**Comment by georgeedwards** [comment]
@vojtechhabarta That's weird. It works for me. Did you follow the steps on the README?

**Comment by kucharzyk** [comment]
Gradle integration works well for me even  for Kotlin classes

Look at my build.gradle: https://raw.githubusercontent.com/shardis/shardis/master/build.gradle

**Comment by vojtechhabarta** [comment]
Thanks @kucharzyk for confirming that Gradle plugin works for you. For me it worked in simple case but @georgeedwards was not able to use it with Azure SDK (and I wasn't able to help him).

**Comment by pburgmer** [comment]
Gradle plugin works for me too. Even in a complex setup with sub projects.

@georgeedwards I compared your build script to mine (which works).

You don't have to define the tool as dependency of your code, just as dependency of your build script. So
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.guava:guava:18.0'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    classpath group: 'cz.habarta.typescript-generator', name: 'typescript-generator-gradle-plugin', version: '1.10.220'
}
```

should be
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.guava:guava:18.0'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
}
```

Maybe, but really just maybe, it is a problem with the order of your code. You apply the plugin before adding it to the classpath. Please try to switch it to something like
```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'cz.habarta.typescript-generator:typescript-generator-gradle-plugin:1.14.251'
    }
}

apply plugin: 'cz.habarta.typescript-generator'

generateTypeScript {
  ...
}
```

Did this fix your problem? I tried your order with my build script and it worked both. Calling it from top-project and from sub-project.

Which Gradle version do you use? I tested my script with 2.12 and 3.1

**Comment by vojtechhabarta** [comment]
Closing the issue, inactive for some time.
